# Generated by Django 4.2.6 on 2023-11-03 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('is_invoice', models.BooleanField(default=True)),
                ('invoice_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('is_receipt', models.BooleanField(default=False)),
                ('receipt_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
            ],
        ),
    ]
